const MAX_SERVERS=5,ID_MAX=9999999;
const $=id=>document.getElementById(id);
const now=()=>new Date().toLocaleTimeString([],{hour12:false});
function cookieGet(name){return document.cookie.split("; ").find(x=>x.startsWith(name+"="))?.split("=")[1]||null}
function cookieSet(name,value,days=3650){document.cookie=name+"="+value+"; max-age="+days*86400+"; path=/; SameSite=Lax"}
function makeId(){return String(Math.floor(Math.random()*ID_MAX)+1).padStart(7,"0")}
let userId=cookieGet("neox_user_id"); if(!/^\d{1,7}$/.test(userId||"")||+userId<1||+userId>ID_MAX){userId=makeId();cookieSet("neox_user_id",userId)}
const storageKey=()=>`neox-cloud-v1:${userId}`;
const baseServer=(n)=>({id:n,name:"NEOX-"+userId+"-"+String(n).padStart(2,"0"),online:true,startedAt:Date.now(),cpu:25+Math.random()*25,ram:25+Math.random()*25,storage:20+Math.random()*30,latency:10+Math.random()*20,bandwidth:500+Math.random()*500,events:0,hostname:"neox-server-"+n,mode:"Standard",autoEvents:true,notifications:true,processes:[["101","neox-kernel","running"],["204","networkd","running"],["310","web-service","running"],["412","cloud-console","running"]],files:[["/system/kernel.neox","2.4 MB"],["/config/server.json","8 KB"],["/logs/boot.log","14 KB"],["/home/readme.txt","3 KB"]],users:[["admin","owner"],[userId,"operator"]],logs:[],incidents:[]});
function load(){try{const x=JSON.parse(localStorage.getItem(storageKey())||"null");if(x?.servers?.length===MAX_SERVERS)return x}catch{}return {active:0,servers:Array.from({length:MAX_SERVERS},(_,i)=>baseServer(i+1))}}
let data=load();data.servers.forEach(s=>{s.startedAt=s.startedAt||Date.now();s.logs=s.logs||[];s.incidents=s.incidents||[]});
let active=data.active||0; let state=()=>data.servers[active]; let eventTimer=null;
function persist(){localStorage.setItem(storageKey(),JSON.stringify(data))}
function print(t,cls=""){const e=document.createElement("div");e.className="line "+cls;e.textContent=t;$("output").appendChild(e);$("output").scrollTop=$("output").scrollHeight}
function log(t,type=""){const s=state();s.logs.unshift({t:now(),text:t,type});s.logs=s.logs.slice(0,80);s.events=(s.events||0)+1;$("eventCount").textContent=s.events+" events";renderLogs();persist()}
function setOnline(v){state().online=v;$("stateText").textContent=v?"ONLINE":"OFFLINE";$("stateDot").style.background=v?"#49d98c":"#e05c68";$("stateDot").style.boxShadow=v?"0 0 12px #49d98c":"0 0 12px #e05c68";$("promptState").textContent=v?"ready":"server offline";renderServers();persist()}
function renderServers(){const box=$("serverGrid");box.innerHTML="";data.servers.forEach((s,i)=>{const e=document.createElement("div");e.className="server-card "+(i===active?"active ":"")+(s.online?"":"offline");e.innerHTML=`<b>${s.name}</b><span>${s.online?"ONLINE":"OFFLINE"} · ${Math.round(s.cpu)}% CPU</span><div class="mini"><i style="width:${Math.round(s.cpu)}%"></i></div>`;e.onclick=()=>{active=i;data.active=i;render();print("switched to "+s.name,"warn");persist()};box.appendChild(e)});$("serverCount").textContent=MAX_SERVERS+"/5";$("userId").textContent="NEOX-"+userId}
function metrics(){const s=state();if(s.online){const load=s.mode==="Performance"?1.7:s.mode==="Eco"?.55:1;s.cpu=Math.max(5,Math.min(96,s.cpu+(Math.random()*10-5)*load));s.ram=Math.max(10,Math.min(88,s.ram+(Math.random()*5-2.5)));s.latency=Math.max(4,Math.min(120,s.latency+(Math.random()*8-4)));s.bandwidth=Math.max(50,Math.min(2000,s.bandwidth+(Math.random()*100-50)))}$("cpu").textContent=Math.round(s.cpu)+"%";$("ram").textContent=Math.round(s.ram)+"%";$("storage").textContent=Math.round(s.storage)+"%";$("latency").textContent=Math.round(s.latency)+" ms";$("bandwidth").textContent=Math.round(s.bandwidth)+" Mbps";$("cpuBar").style.width=s.cpu+"%";$("ramBar").style.width=s.ram+"%";$("storageBar").style.width=s.storage+"%";const up=s.online?Math.floor((Date.now()-s.startedAt)/1000):0;$("clock").textContent=now();$("uptime").textContent="";renderServers();renderTables()}
function renderLogs(){const s=state();$("logs").innerHTML=s.logs.slice(0,50).map(x=>`<div class="log"><span class="time">${x.t}</span><b>${x.text}</b></div>`).join("");$("eventCount").textContent=(s.events||0)+" events"}
function renderTables(){const s=state();$("processCount").textContent=s.processes.length+" processes";$("processes").innerHTML=s.processes.map(x=>`<div class="row"><span>PID ${x[0]} · ${x[1]}</span><span>${x[2]}</span></div>`).join("");$("network").innerHTML=[["interface","neox0"],["status",s.online?"connected":"offline"],["latency",Math.round(s.latency)+" ms"],["bandwidth",Math.round(s.bandwidth)+" Mbps"],["mode","simulated LAN"]].map(x=>`<div class="row"><span>${x[0]}</span><span>${x[1]}</span></div>`).join("");$("files").innerHTML=s.files.map(x=>`<div class="row"><span>${x[0]}</span><span>${x[1]}</span></div>`).join("");$("storageText").textContent=s.files.length+" files";$("users").innerHTML=s.users.map(x=>`<div class="row"><span>${x[0]}</span><span>${x[1]}</span></div>`).join("")}
function help(){print(["help       commands","status     server status","servers    list five virtual servers","switch N   select server 1-5","start/stop  power server","restart    restart server","processes  simulated process list","kill PID   stop a simulated process","network    network details","files      virtual file list","touch NAME  create virtual file","users      local users","logs       recent logs","event      simulate server event","incident    create simulated fault","recover     recover fault","diagnose    run diagnostics","update     simulate system update","notify     show notifications","settings   show configuration","mode X     change Standard/Performance/Eco/Maintenance","clear      clear console","reset      reset current server","whoami     show NEOX user ID"].join("\n"))}
function command(raw){const a=raw.trim().split(/\s+/),c=(a[0]||"").toLowerCase();if(!c)return;print("neox-cloud> "+raw,"cmd");const s=state();switch(c){case"help":help();break;case"whoami":print("NEOX-"+userId);break;case"status":print(`server: ${s.name}\nstate: ${s.online?"ONLINE":"OFFLINE"}\ncpu: ${Math.round(s.cpu)}%\nram: ${Math.round(s.ram)}%\nstorage: ${Math.round(s.storage)}%\nlatency: ${Math.round(s.latency)}ms\nmode: ${s.mode}`);break;case"servers":data.servers.forEach((x,i)=>print(`${i+1}. ${x.name} [${x.online?"ONLINE":"OFFLINE"}]`));break;case"switch":{const n=+a[1]-1;if(n>=0&&n<MAX_SERVERS){active=n;data.active=n;render();print("selected "+state().name,"warn");persist()}else print("use switch 1-5","error");break}case"start":if(s.online)print("server already online");else{ s.startedAt=Date.now();setOnline(true);log(s.name+" started");print("server started","warn")}break;case"stop":if(!s.online)print("server already offline");else{setOnline(false);log(s.name+" stopped");print("server stopped","warn")}break;case"restart":setOnline(false);log(s.name+" restarting");print("restarting...","warn");setTimeout(()=>{s.startedAt=Date.now();setOnline(true);log(s.name+" online");print("server online","warn")},900);break;case"processes":print(s.processes.map(x=>x.join("   ")).join("\n"));break;case"kill":{const p=a[1],idx=s.processes.findIndex(x=>x[0]===p);if(idx<0)print("PID not found","error");else{const old=s.processes[idx];s.processes[idx][2]="stopped";log("process "+p+" stopped");print(old[1]+" stopped","warn");renderTables();persist()}break}case"network":print(`interface: neox0\nstatus: ${s.online?"connected":"offline"}\nlatency: ${Math.round(s.latency)}ms\nbandwidth: ${Math.round(s.bandwidth)}Mbps`);break;case"files":print(s.files.map(x=>x[0]+"   "+x[1]).join("\n"));break;case"touch":{const name=a[1];if(!name)print("usage: touch NAME","error");else{s.files.push(["/home/"+name,"1 KB"]);log("created /home/"+name);renderTables();persist();print("file created","warn")}break}case"users":print(s.users.map(x=>x[0]+"   "+x[1]).join("\n"));break;case"logs":$("logs").scrollIntoView({behavior:"smooth"});break;case"event":randomEvent(true);break;case"incident":incident();break;case"recover":recover();break;case"diagnose":diagnose();break;case"update":updateServer();break;case"notify":print(s.notifications?"notifications enabled":"notifications disabled");break;case"settings":print(`hostname: ${s.hostname}\nmode: ${s.mode}\nauto events: ${s.autoEvents}\nnotifications: ${s.notifications}`);break;case"mode":{const m=a[1];if(["standard","performance","eco","maintenance"].includes((m||"").toLowerCase())){s.mode=m[0].toUpperCase()+m.slice(1).toLowerCase();log("mode changed to "+s.mode);render();persist()}else print("mode: Standard | Performance | Eco | Maintenance","error");break}case"clear":$("output").innerHTML="";break;case"reset":resetServer();break;default:print("unknown command. type help","error")}}
function randomEvent(manual=false){const s=state(),events=["backup completed","health check passed","cache optimized","network route refreshed","log rotation completed","process supervisor checked"];const msg=events[Math.floor(Math.random()*events.length)];s.cpu=Math.max(5,s.cpu-2);log(s.name+": "+msg);if(manual)print(msg,"warn");persist()}
function incident(){const s=state();const incidents=["high CPU detected","network jitter detected","storage warning","service restart required"];const msg=incidents[Math.floor(Math.random()*incidents.length)];s.incidents=[msg];$("incidentState").textContent="incident";$("incidents").innerHTML='<span class="warntext">⚠ '+msg+'</span>';log(s.name+": "+msg,"warn");persist()}
function recover(){const s=state();s.incidents=[];$("incidentState").textContent="stable";$("incidents").textContent="No active incidents.";log(s.name+": recovery completed");print("recovery completed","warn");persist()}
function diagnose(){const s=state();$("diagnostics").innerHTML='<span class="ok">✓ kernel</span> OK<br><span class="ok">✓ network</span> '+(s.online?"OK":"OFFLINE")+'<br><span class="ok">✓ storage</span> '+Math.round(s.storage)+'% used<br><span class="ok">✓ process supervisor</span> OK<br><span class="ok">✓ persistence</span> localStorage OK';log(s.name+": diagnostics completed");persist()}
function updateServer(){const s=state();print("checking NEOX update...","warn");setTimeout(()=>{log(s.name+": NEOX system update simulated");print("update 1.0.0 -> 1.0.1 complete","warn");persist()},700)}
function resetServer(){const n=state().id;data.servers[n-1]=baseServer(n);active=n-1;data.active=active;render();log("server reset");print("server reset","warn");persist()}
function render(){const s=state();renderServers();renderLogs();renderTables();$("hostname").value=s.hostname;$("serverMode").value=s.mode;$("autoEvents").checked=s.autoEvents;$("notifications").checked=s.notifications;$("stateText").textContent=s.online?"ONLINE":"OFFLINE";$("stateDot").style.background=s.online?"#49d98c":"#e05c68";$("stateDot").style.boxShadow=s.online?"0 0 12px #49d98c":"0 0 12px #e05c68";$("promptState").textContent=s.online?"ready":"server offline";$("diagnostics").textContent="System diagnostics ready.";if(s.incidents.length){$("incidentState").textContent="incident";$("incidents").innerHTML='<span class="warntext">⚠ '+s.incidents[0]+'</span>'}else{$("incidentState").textContent="stable";$("incidents").textContent="No active incidents."}metrics()}
$("commandForm").addEventListener("submit",e=>{e.preventDefault();command($("command").value);$("command").value=""});
$("diagnoseBtn").onclick=diagnose;
$("saveSettings").onclick=()=>{const s=state();s.hostname=$("hostname").value.trim()||"neox-server";s.mode=$("serverMode").value;s.autoEvents=$("autoEvents").checked;s.notifications=$("notifications").checked;log(s.name+": settings saved");persist();render()};
$("resetServer").onclick=()=>{if(confirm("Reset this simulated server?"))resetServer()};
$("newIdBtn").onclick=()=>{if(confirm("Create a new NEOX ID? This creates a new local profile.")){userId=makeId();cookieSet("neox_user_id",userId);data=load();active=data.active||0;render();print("new identity: NEOX-"+userId,"warn")}};
setInterval(()=>{metrics();const s=state();if(s.autoEvents&&s.online&&Math.random()<.08)randomEvent();if(s.autoEvents&&s.online&&Math.random()<.015)incident()},1000);
render();if(!state().logs.length){log("profile NEOX-"+userId+" initialized");log(state().name+" initialized")}print("NEOX Cloud Live v1.0");print("5 persistent virtual servers ready.","warn");print("Identity: NEOX-"+userId,"warn");