const state={online:true,startedAt:Date.now()-((2*3600+31*60+44)*1000),events:0,cpu:41,ram:38,storage:52};
const $=id=>document.getElementById(id);
function time(){return new Date().toLocaleTimeString([], {hour12:false})}
function print(text,cls=""){const el=document.createElement("div");el.className="line "+cls;el.textContent=text;$("output").appendChild(el);$("output").scrollTop=$("output").scrollHeight}
function log(text){const el=document.createElement("div");el.className="log";el.innerHTML='<span class="time">'+time()+'</span><b>'+text.replaceAll("<","&lt;")+'</b>';$("logs").prepend(el);$("eventCount").textContent=(++state.events)+" events"}
function setState(online){state.online=online;$("stateText").textContent=online?"ONLINE":"OFFLINE";$("stateDot").style.background=online?"#49d98c":"#e05c68";$("stateDot").style.boxShadow=online?"0 0 12px #49d98c":"0 0 12px #e05c68";$("promptState").textContent=online?"ready":"server offline"}
function metrics(){if(state.online){state.cpu=Math.max(8,Math.min(92,state.cpu+(Math.random()*12-6)));state.ram=Math.max(18,Math.min(78,state.ram+(Math.random()*6-3)))}$("cpu").textContent=Math.round(state.cpu)+"%";$("ram").textContent=Math.round(state.ram)+"%";$("cpuBar").style.width=state.cpu+"%";$("ramBar").style.width=state.ram+"%";const s=Math.floor((Date.now()-state.startedAt)/1000);$("uptime").textContent=[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(n=>String(n).padStart(2,"0")).join(":")}
function help(){["help       show commands","status     server state and metrics","start      start the server","stop       stop the server","restart    restart the server","logs       show recent events","processes  show simulated processes","network    show simulated network","clear      clear console"].forEach(x=>print(x))}
function command(raw){const c=raw.trim().toLowerCase();if(!c)return;print("neox-cloud> "+raw,"cmd");switch(c){case"help":help();break;case"status":print('server: NEOX-01\\nstate: '+(state.online?"ONLINE":"OFFLINE")+'\\ncpu: '+Math.round(state.cpu)+'%\\nram: '+Math.round(state.ram)+'%');break;case"start":if(state.online)print("server already online");else{state.startedAt=Date.now();setState(true);log("NEOX-01 started");print("server started","warn")}break;case"stop":if(!state.online)print("server already offline");else{setState(false);log("NEOX-01 stopped");print("server stopped","warn")}break;case"restart":setState(false);log("NEOX-01 restarting");print("restarting...","warn");setTimeout(()=>{state.startedAt=Date.now();setState(true);log("NEOX-01 online");print("server online","warn")},1200);break;case"logs":document.querySelector(".logs").scrollIntoView({behavior:"smooth"});break;case"processes":print("PID   PROCESS\\n101   neox-kernel\\n204   networkd\\n310   web-service\\n412   cloud-console");break;case"network":print("interface: neox0\\nstatus: connected\\nlatency: 18ms");break;case"clear":$("output").innerHTML="";break;default:print("unknown command. type help")}}
$("commandForm").addEventListener("submit",e=>{e.preventDefault();command($("command").value);$("command").value=""});
print("NEOX Cloud Live v0.1");print("Shared simulation server NEOX-01 is online.","warn");log("NEOX-01 initialized");
setInterval(()=>{$("clock").textContent=time();metrics()},1000);metrics();